####################
##### Locations

#Filepath to coding folder
local_file_path: "/content/Subnational-Statistics-and-Analysis/clustering_and_nearest_neighbours"

#Filepath to inputs (data and geography files)
inputs_file_path: "/content/Subnational-Statistics-and-Analysis/clustering_and_nearest_neighbours/inputs"

#Filepath to where you want your outputs to go
outputs_file_path: "/content/Subnational-Statistics-and-Analysis/clustering_and_nearest_neighbours/outputs"

###################
##### Geography files

### Lower to upper tier local authority lookup
#Name of the upper tier LA lookup used for imputation
lower_tier_to_upper_tier_lookup: "LTLA25_to_UTLA25_lookup"
#Name of the upper tier code column from lower tier to upper tier lookup
upper_tier_code_column_name: "CTYUA25CD"  
#Name of the lower tier code column from lower tier to upper tier lookup
lower_tier_code_column_name: "LAD25CD"

### Geog repo
#Name of geography repository used as a repo for wanted geographies
#Include all the geographies you want to output, the original version to run needs ITL1, LTLA and UTLA
#This file is not used as a lookup and rows do not match across geography
#Each geography needs a code column and a names column
Geog_repo: "names_and_codes_repo_25"
# column with ITL1 data required for ITL1 summary table
ITL1_col: "ITL1"
#Set the geography you want to work with
#This geography must already be in your data
#This will be the code and name column in your geog repo
#Data is filtered to just this geography in the early stages
desired_geog: "LTLA25CD"
desired_geog_nm: "LTLA25NM"


### Shapefile (Used in clustering only)
#Name of the shapefile (no .___ extension, just file name)
#Currently this is lower tier local authority
#This is only used for clustering and will need to match the geography you cluster on
shapefile: "LAD_MAY_2025_UK_BGC_V2" 
#Area column code from shapefile so it can be dropped 
shapefile_area_col: "LAD25CD" 

###################
##### Data 

##Name of the table containing the input data         
subnational_indicators_table_name: "subnational_indicators"

##################
### Metrics

#Here you specify the metric column name for each of your desired variables
#Can be adapted for other metrics provided they are included in the data
custom_metrics_to_run:
  - "Child poverty (AHC relative)"
